name: Build & Push
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pracharya2601/nextjs-starter:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to digital ocean droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd "$HOME/starter"
            docker compose down
            docker pull pracharya2601/nextjs-starter:latest
            docker compose up -d
            docker system prune -f
